[package]
name = "modplayer-audio-io"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
modplayer-engine = { path = "../modplayer-engine", version = "0.1.0" }
modplayer-audio-source-synthetic = { path = "../modplayer-audio-source-synthetic", version = "0.1.0" }
cpal.workspace = true
thiserror.workspace = true

[dev-dependencies]
modplayer-audio-source = { path = "../modplayer-audio-source", version = "0.1.0" }
rtrb.workspace = true
