// SPDX-License-Identifier: MIT OR Apache-2.0
#![allow(clippy::unwrap_used, clippy::expect_used, clippy::disallowed_methods)]

//! `advance_is_consistent_with_fr013_fr014` (SC-011,
//! contracts/transport-and-queue.md §4): random sequences of up to 64
//! operations over fixtures of up to 12 tracks (with duplicates and
//! unavailable flags) must never break `Queue`'s invariants
//! (data-model.md §2.2):
//! - `advance` never returns a removed or unavailable item as the new
//!   `current`.
//! - The play-next block stays contiguous immediately after `current`.
//! - `history.len() <= HISTORY_LIMIT`.
//! - Every context item is visited at most once per shuffle cycle (no
//!   duplicate `MoveTo` for the same still-present item between two
//!   wraps).

use modplayer_audio_source::{Availability, Repeat, TrackId, TrackRef};
use modplayer_core::queue::{AdvanceReason, HISTORY_LIMIT, PlaybackChange, Queue, QueueRng};
use proptest::prelude::*;

/// A `QueueRng` driven by a proptest-generated byte stream, so shuffles
/// are reproducible from the failing input proptest reports.
struct StepRng<'a> {
    bytes: &'a [u8],
    pos: usize,
}

impl QueueRng for StepRng<'_> {
    fn next_u64(&mut self) -> u64 {
        let mut buf = [0u8; 8];
        for slot in &mut buf {
            *slot = self
                .bytes
                .get(self.pos % self.bytes.len().max(1))
                .copied()
                .unwrap_or(0);
            self.pos += 1;
        }
        u64::from_le_bytes(buf)
    }
}

fn track(n: usize) -> TrackRef {
    TrackRef::new(
        TrackId::new(format!("spotify:track:{n}")).unwrap_or_else(|_| unreachable!()),
        format!("Title {n}"),
        vec!["Artist".to_string()],
        None,
        None,
        180_000,
        Availability::Available,
    )
}

/// One scripted operation over a small fixture (up to 12 tracks, indices
/// may repeat to exercise duplicates).
#[derive(Debug, Clone)]
enum Op {
    Advance(AdvanceReason),
    SetShuffle(bool),
    SetRepeat(Repeat),
    MarkUnavailable(usize),
    PlayNextTrack(usize),
    SkipBack(u32),
}

fn op_strategy() -> impl Strategy<Value = Op> {
    prop_oneof![
        prop_oneof![
            Just(AdvanceReason::TrackEnd),
            Just(AdvanceReason::Skip),
            Just(AdvanceReason::SeekPastEnd),
        ]
        .prop_map(Op::Advance),
        any::<bool>().prop_map(Op::SetShuffle),
        prop_oneof![Just(Repeat::Off), Just(Repeat::One), Just(Repeat::All)]
            .prop_map(Op::SetRepeat),
        (0usize..12).prop_map(Op::MarkUnavailable),
        (0usize..12).prop_map(Op::PlayNextTrack),
        (0u32..6_000).prop_map(Op::SkipBack),
    ]
}

proptest! {
    #![proptest_config(ProptestConfig::with_cases(200))]

    #[test]
    fn advance_is_consistent_with_fr013_fr014(
        fixture_len in 1usize..=12,
        // Duplicates: fixture ids drawn with repeats allowed via modulo.
        duplicate_seed in 0usize..12,
        ops in prop::collection::vec(op_strategy(), 0..=64),
        rng_bytes in prop::collection::vec(any::<u8>(), 8..64),
    ) {
        let mut q = Queue::new();
        let tracks: Vec<TrackRef> = (0..fixture_len)
            .map(|i| track(i % (duplicate_seed + 1).max(1)))
            .collect();
        q.replace_context(tracks);
        let mut rng = StepRng { bytes: &rng_bytes, pos: 0 };

        for op in ops {
            match op {
                Op::Advance(reason) => {
                    let change = q.advance(reason, &mut rng);
                    if let PlaybackChange::MoveTo(_) = change.playback {
                        // The real invariant is per-item, not per-track-id:
                        // duplicates mean two different items can share a
                        // `TrackId` while only one of them is unavailable
                        // (data-model.md §2.1's `unavailable` flag is set
                        // "on every item with that id" *at the time*
                        // `mark_unavailable` runs, not retroactively on
                        // items added later).
                        let current = q.current().expect("MoveTo implies a current item");
                        prop_assert!(
                            !current.unavailable,
                            "advance must never land on an item still marked unavailable"
                        );
                    }
                }
                Op::SetShuffle(on) => {
                    q.set_shuffle(on, &mut rng);
                }
                Op::SetRepeat(mode) => {
                    q.set_repeat(mode);
                }
                Op::MarkUnavailable(index) => {
                    let ids: Vec<TrackId> = q
                        .effective_order()
                        .iter()
                        .map(|i| i.track.id.clone())
                        .collect();
                    if let Some(id) = ids.get(index % ids.len().max(1)) {
                        q.mark_unavailable(id, &mut rng);
                    }
                }
                Op::PlayNextTrack(seed) => {
                    q.play_next_track(track(seed));
                }
                Op::SkipBack(position_ms) => {
                    q.skip_back(position_ms);
                }
            }

            // Invariant, after every single operation: the play-next block
            // is contiguous immediately after `current` in the effective
            // order (data-model.md §2.2).
            let order = q.effective_order();
            let mut past_play_next = false;
            let mut seen_current = false;
            for item in order.iter().skip(if q.current().is_some() { 1 } else { 0 }) {
                seen_current = true;
                match item.origin {
                    modplayer_core::queue::Origin::PlayNext if past_play_next => {
                        prop_assert!(
                            false,
                            "play-next items must be contiguous immediately after current"
                        );
                    }
                    modplayer_core::queue::Origin::PlayNext => {}
                    _ => past_play_next = true,
                }
            }
            let _ = seen_current;

            prop_assert!(
                q.history().count() <= HISTORY_LIMIT,
                "history must never exceed {}",
                HISTORY_LIMIT
            );
        }
    }
}
