// SPDX-License-Identifier: MIT OR Apache-2.0
// Build-time tooling, never shipped: a panic here is the intended, fail-
// fast response to a malformed schema (clippy.toml's disallowed-methods
// note exempts "tests and main" for the same reason).
#![allow(clippy::unwrap_used, clippy::expect_used, clippy::disallowed_methods)]

//! Parses `api/v1.toml` — the one machine-readable definition of the
//! plugin API (Constitution IX, research R6) — into `OUT_DIR/generated.rs`:
//! the `Permission`, `RequestKind` and `EventKind` enums plus their
//! lookup tables. `src/api.rs` `include!`s the result.
//!
//! G8 (contracts/gateway-and-runtime.md): this build **fails** if a
//! request or event names a permission outside the 25-entry catalog, or a
//! request names a rate category outside the five `RateCategory` variants.

use std::collections::BTreeSet;
use std::env;
use std::fmt::Write as _;
use std::path::PathBuf;

use serde::Deserialize;

#[derive(Debug, Deserialize)]
struct Schema {
    api_version: ApiVersionDto,
    #[allow(dead_code)]
    refusal_codes: Vec<String>,
    permission: Vec<PermissionDto>,
    request: Vec<RequestDto>,
    event: Vec<EventDto>,
}

#[derive(Debug, Deserialize)]
struct ApiVersionDto {
    major: u16,
    minor: u16,
}

#[derive(Debug, Deserialize)]
struct PermissionDto {
    name: String,
    #[allow(dead_code)]
    category: String,
    operable: bool,
}

#[derive(Debug, Deserialize)]
struct RequestDto {
    name: String,
    namespace: String,
    method: String,
    #[serde(default)]
    requires: Option<String>,
    needs_focus: bool,
    category: String,
}

#[derive(Debug, Deserialize)]
struct EventDto {
    name: String,
    #[serde(default)]
    requires: Option<String>,
    #[allow(dead_code)]
    payload: Vec<String>,
}

/// `"playback.observe"` -> `"PlaybackObserve"` (each dot-separated label
/// PascalCased and concatenated).
fn pascal_case(dotted: &str) -> String {
    dotted
        .split(['.', '_'])
        .map(|part| {
            let mut chars = part.chars();
            match chars.next() {
                Some(first) => first.to_ascii_uppercase().to_string() + chars.as_str(),
                None => String::new(),
            }
        })
        .collect()
}

const RATE_CATEGORIES: &[&str] = &[
    "transport",
    "markers",
    "effects",
    "state",
    "timers",
    "ui",
    "notify",
];

fn rate_category_variant(name: &str) -> &'static str {
    match name {
        "transport" => "Transport",
        "markers" => "Markers",
        "effects" => "Effects",
        "state" => "State",
        "timers" => "Timers",
        "ui" => "Ui",
        "notify" => "Notify",
        other => panic!("api/v1.toml: unknown rate category '{other}' (G8)"),
    }
}

fn main() {
    println!("cargo:rerun-if-changed=api/v1.toml");

    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let schema_path = manifest_dir.join("api/v1.toml");
    let text = std::fs::read_to_string(&schema_path)
        .unwrap_or_else(|e| panic!("failed to read {}: {e}", schema_path.display()));
    let schema: Schema =
        toml::from_str(&text).unwrap_or_else(|e| panic!("failed to parse api/v1.toml: {e}"));

    let permission_names: BTreeSet<&str> =
        schema.permission.iter().map(|p| p.name.as_str()).collect();

    // G8: every request's `requires` and `category` must exist in the
    // catalog / the five rate categories.
    for r in &schema.request {
        if let Some(req) = &r.requires
            && !permission_names.contains(req.as_str())
        {
            panic!(
                "api/v1.toml: request '{}' requires unknown permission '{req}' (G8)",
                r.name
            );
        }
        if !RATE_CATEGORIES.contains(&r.category.as_str()) {
            panic!(
                "api/v1.toml: request '{}' has unknown category '{}' (G8)",
                r.name, r.category
            );
        }
    }
    // G8: every event's `requires` must exist in the catalog.
    for e in &schema.event {
        if let Some(req) = &e.requires
            && !permission_names.contains(req.as_str())
        {
            panic!(
                "api/v1.toml: event '{}' requires unknown permission '{req}' (G8)",
                e.name
            );
        }
    }

    let mut out = String::new();

    writeln!(
        out,
        "// GENERATED by build.rs from api/v1.toml. Do not edit by hand."
    )
    .unwrap();

    // -- ApiVersion --------------------------------------------------------
    writeln!(
        out,
        "\n/// The plugin API's own version (research R6, contract §1)."
    )
    .unwrap();
    writeln!(
        out,
        "#[derive(Debug, Clone, Copy, PartialEq, Eq)]\npub struct ApiVersion {{ pub major: u16, pub minor: u16 }}"
    )
    .unwrap();
    writeln!(
        out,
        "pub const API_VERSION: ApiVersion = ApiVersion {{ major: {}, minor: {} }};",
        schema.api_version.major, schema.api_version.minor
    )
    .unwrap();

    // -- Permission ----------------------------------------------------------
    writeln!(
        out,
        "\n/// The 25-entry permission catalog (data-model.md §1.1, FR-015)."
    )
    .unwrap();
    writeln!(
        out,
        "#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord)]\npub enum Permission {{"
    )
    .unwrap();
    for p in &schema.permission {
        writeln!(out, "    {},", pascal_case(&p.name)).unwrap();
    }
    writeln!(out, "}}").unwrap();

    writeln!(out, "impl Permission {{").unwrap();
    writeln!(
        out,
        "    /// Every catalog entry, in `api/v1.toml` declaration order."
    )
    .unwrap();
    writeln!(
        out,
        "    pub const ALL: [Permission; {}] = [",
        schema.permission.len()
    )
    .unwrap();
    for p in &schema.permission {
        writeln!(out, "        Permission::{},", pascal_case(&p.name)).unwrap();
    }
    writeln!(out, "    ];\n").unwrap();

    writeln!(
        out,
        "    /// The catalog string, e.g. \"playback.observe\"."
    )
    .unwrap();
    writeln!(out, "    pub const fn name(self) -> &'static str {{").unwrap();
    writeln!(out, "        match self {{").unwrap();
    for p in &schema.permission {
        writeln!(
            out,
            "            Permission::{} => \"{}\",",
            pascal_case(&p.name),
            p.name
        )
        .unwrap();
    }
    writeln!(out, "        }}\n    }}\n").unwrap();

    writeln!(
        out,
        "    /// The Fluent key explaining this permission to the user (R15)."
    )
    .unwrap();
    writeln!(
        out,
        "    pub fn explanation_key(self) -> String {{ format!(\"permission-{{}}\", self.name().replace('.', \"-\")) }}\n"
    )
    .unwrap();

    writeln!(
        out,
        "    /// Whether this slice implements calls needing this permission (FR-015)."
    )
    .unwrap();
    writeln!(out, "    pub const fn operable(self) -> bool {{").unwrap();
    writeln!(out, "        match self {{").unwrap();
    for p in &schema.permission {
        writeln!(
            out,
            "            Permission::{} => {},",
            pascal_case(&p.name),
            p.operable
        )
        .unwrap();
    }
    writeln!(out, "        }}\n    }}\n").unwrap();

    writeln!(
        out,
        "    /// Parse a catalog string (e.g. from a manifest) back into a [`Permission`]."
    )
    .unwrap();
    writeln!(out, "    pub fn parse(s: &str) -> Option<Permission> {{").unwrap();
    writeln!(out, "        match s {{").unwrap();
    for p in &schema.permission {
        writeln!(
            out,
            "            \"{}\" => Some(Permission::{}),",
            p.name,
            pascal_case(&p.name)
        )
        .unwrap();
    }
    writeln!(out, "            _ => None,").unwrap();
    writeln!(out, "        }}\n    }}").unwrap();
    writeln!(out, "}}").unwrap();

    // -- RequestKind -------------------------------------------------------
    writeln!(
        out,
        "\n/// One `RequestKind` per Lua-callable request (data-model.md §1.1)."
    )
    .unwrap();
    writeln!(
        out,
        "#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord)]\npub enum RequestKind {{"
    )
    .unwrap();
    for r in &schema.request {
        writeln!(out, "    {},", r.name).unwrap();
    }
    writeln!(out, "}}").unwrap();

    writeln!(out, "impl RequestKind {{").unwrap();
    writeln!(
        out,
        "    /// Every request kind, in `api/v1.toml` declaration order — the runtime's\n    /// dispatcher matches exhaustively over this so a schema addition without a\n    /// binding fails to compile (design note 1)."
    )
    .unwrap();
    writeln!(
        out,
        "    pub const ALL: [RequestKind; {}] = [",
        schema.request.len()
    )
    .unwrap();
    for r in &schema.request {
        writeln!(out, "        RequestKind::{},", r.name).unwrap();
    }
    writeln!(out, "    ];\n").unwrap();

    writeln!(
        out,
        "    /// The permission this call needs, or `None` only for timers/`debug_probe`."
    )
    .unwrap();
    writeln!(
        out,
        "    pub const fn requires(self) -> Option<Permission> {{"
    )
    .unwrap();
    writeln!(out, "        match self {{").unwrap();
    for r in &schema.request {
        let value = match &r.requires {
            Some(p) => format!("Some(Permission::{})", pascal_case(p)),
            None => "None".to_string(),
        };
        writeln!(out, "            RequestKind::{} => {},", r.name, value).unwrap();
    }
    writeln!(out, "        }}\n    }}\n").unwrap();

    writeln!(
        out,
        "    /// Whether the calling plugin must currently hold transport focus (G2)."
    )
    .unwrap();
    writeln!(out, "    pub const fn needs_focus(self) -> bool {{").unwrap();
    writeln!(out, "        match self {{").unwrap();
    for r in &schema.request {
        writeln!(
            out,
            "            RequestKind::{} => {},",
            r.name, r.needs_focus
        )
        .unwrap();
    }
    writeln!(out, "        }}\n    }}\n").unwrap();

    writeln!(
        out,
        "    /// The rolling-1s rate-limit bucket this call is counted under (G5)."
    )
    .unwrap();
    writeln!(
        out,
        "    pub const fn category(self) -> crate::limiter::RateCategory {{"
    )
    .unwrap();
    writeln!(out, "        match self {{").unwrap();
    for r in &schema.request {
        writeln!(
            out,
            "            RequestKind::{} => crate::limiter::RateCategory::{},",
            r.name,
            rate_category_variant(&r.category)
        )
        .unwrap();
    }
    writeln!(out, "        }}\n    }}\n").unwrap();

    writeln!(
        out,
        "    /// The Lua-facing `(namespace, method)` path, e.g. `(\"transport\", \"seek\")`;\n    /// an empty namespace is a call directly on `api` (`debug_probe`)."
    )
    .unwrap();
    writeln!(
        out,
        "    pub const fn lua_path(self) -> (&'static str, &'static str) {{"
    )
    .unwrap();
    writeln!(out, "        match self {{").unwrap();
    for r in &schema.request {
        writeln!(
            out,
            "            RequestKind::{} => (\"{}\", \"{}\"),",
            r.name, r.namespace, r.method
        )
        .unwrap();
    }
    writeln!(out, "        }}\n    }}\n").unwrap();

    writeln!(
        out,
        "    /// A stable diagnostic name, e.g. \"transport.seek\"."
    )
    .unwrap();
    writeln!(out, "    pub const fn name(self) -> &'static str {{").unwrap();
    writeln!(out, "        match self {{").unwrap();
    for r in &schema.request {
        let full = if r.namespace.is_empty() {
            r.method.clone()
        } else {
            format!("{}.{}", r.namespace, r.method)
        };
        writeln!(out, "            RequestKind::{} => \"{}\",", r.name, full).unwrap();
    }
    writeln!(out, "        }}\n    }}").unwrap();
    writeln!(out, "}}").unwrap();

    // -- EventKind -----------------------------------------------------------
    writeln!(
        out,
        "\n/// One `EventKind` per host -> plugin event (data-model.md §1.1)."
    )
    .unwrap();
    writeln!(
        out,
        "#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord)]\npub enum EventKind {{"
    )
    .unwrap();
    for e in &schema.event {
        writeln!(out, "    {},", e.name).unwrap();
    }
    writeln!(out, "}}").unwrap();

    writeln!(out, "impl EventKind {{").unwrap();
    writeln!(
        out,
        "    pub const ALL: [EventKind; {}] = [",
        schema.event.len()
    )
    .unwrap();
    for e in &schema.event {
        writeln!(out, "        EventKind::{},", e.name).unwrap();
    }
    writeln!(out, "    ];\n").unwrap();

    writeln!(
        out,
        "    /// The permission a plugin must hold to receive this event (C4/FR-028)."
    )
    .unwrap();
    writeln!(
        out,
        "    pub const fn requires(self) -> Option<Permission> {{"
    )
    .unwrap();
    writeln!(out, "        match self {{").unwrap();
    for e in &schema.event {
        let value = match &e.requires {
            Some(p) => format!("Some(Permission::{})", pascal_case(p)),
            None => "None".to_string(),
        };
        writeln!(out, "            EventKind::{} => {},", e.name, value).unwrap();
    }
    writeln!(out, "        }}\n    }}\n").unwrap();

    writeln!(
        out,
        "    /// The Lua event name, e.g. \"track_changed\" (`api.on(name, ...)`)."
    )
    .unwrap();
    writeln!(out, "    pub const fn name(self) -> &'static str {{").unwrap();
    writeln!(out, "        match self {{").unwrap();
    for e in &schema.event {
        writeln!(
            out,
            "            EventKind::{} => \"{}\",",
            e.name,
            to_snake_case(&e.name)
        )
        .unwrap();
    }
    writeln!(out, "        }}\n    }}").unwrap();
    writeln!(out, "}}").unwrap();

    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR"));
    std::fs::write(out_dir.join("generated.rs"), out).expect("write generated.rs");
}

/// `"TrackChanged"` -> `"track_changed"`, `"ReadyAck"` -> `"ready_ack"`.
fn to_snake_case(pascal: &str) -> String {
    let mut out = String::new();
    for (i, ch) in pascal.chars().enumerate() {
        if ch.is_ascii_uppercase() {
            if i != 0 {
                out.push('_');
            }
            out.push(ch.to_ascii_lowercase());
        } else {
            out.push(ch);
        }
    }
    out
}
